### ISSUE TITLE
hidding hypothesis on modular page

### ISSUE THREAD

**Issue by JOduMonT** [hibbitts-design/grav-plugin-hypothesis#1]
Hi Paul;
 
I discover this plug-in and hypothesis at the same time which make a beautiful job for note taking (I wish all website have this)

Anyway;
just to say on **Modular Page**
in **Page Options (Admin Panel)**
the your **Option** to Display or not Hypothesis don't appear.

However by adding the frontmatter line : `hide_hypothesis: true` works and make Hypothesis disappear.

Have a nice day

Jonathan

**Comment by JOduMonT** [comment]
sorry; in fact it was, probably a cache issue, because now I have the option ;)

**Comment by paulhibbitts** [comment]
Grear to hear everything is working @jodumont !
